import Head from 'next/head'
import Hero from '../components/Hero'
import { VStack } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ComponentsLibrary</title>
        <meta name="description" content="Generated by codeFish" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
